// Spanish → English bundle: top ~1 000 words for instant offline lookup.
// Format: [word, [translation, pos]]
// pos: noun | verb | adj | adv | prep | conj | pron | art | num | int
const ES_BUNDLE = new Map([

// ── Articles ──────────────────────────────────────────────────────────────────
  ['el',['the','art']],['la',['the','art']],['los',['the','art']],['las',['the','art']],
  ['un',['a','art']],['una',['a','art']],['unos',['some','art']],['unas',['some','art']],
  ['del',['of the','prep']],['al',['to the','prep']],

// ── Pronouns ──────────────────────────────────────────────────────────────────
  ['yo',['I','pron']],['tú',['you','pron']],['él',['he','pron']],['ella',['she','pron']],
  ['nosotros',['we','pron']],['nosotras',['we','pron']],
  ['ellos',['they','pron']],['ellas',['they','pron']],
  ['usted',['you (formal)','pron']],['ustedes',['you all','pron']],
  ['me',['me','pron']],['te',['you','pron']],['se',['himself/herself','pron']],
  ['nos',['us','pron']],['le',['him/her','pron']],['les',['them','pron']],
  ['lo',['him/it','pron']],['los',['them','pron']],
  ['mi',['my','pron']],['tu',['your','pron']],['su',['his/her/their','pron']],
  ['mis',['my','pron']],['tus',['your','pron']],['sus',['his/her/their','pron']],
  ['nuestro',['our','pron']],['nuestra',['our','pron']],
  ['este',['this','pron']],['esta',['this','pron']],
  ['estos',['these','pron']],['estas',['these','pron']],
  ['ese',['that','pron']],['esa',['that','pron']],
  ['esos',['those','pron']],['esas',['those','pron']],
  ['esto',['this','pron']],['eso',['that','pron']],
  ['quien',['who','pron']],['quienes',['who','pron']],
  ['algo',['something','pron']],['alguien',['someone','pron']],
  ['nada',['nothing','pron']],['nadie',['nobody','pron']],
  ['todo',['everything','pron']],['todos',['everyone/all','pron']],
  ['toda',['all','pron']],['todas',['all','pron']],
  ['mismo',['same/himself','pron']],['misma',['same/herself','pron']],

// ── Prepositions ──────────────────────────────────────────────────────────────
  ['a',['to/at','prep']],['ante',['before/in front of','prep']],
  ['bajo',['under','prep']],['con',['with','prep']],['contra',['against','prep']],
  ['de',['of/from','prep']],['desde',['from/since','prep']],['durante',['during','prep']],
  ['en',['in/on','prep']],['entre',['between','prep']],['hacia',['toward','prep']],
  ['hasta',['until/up to','prep']],['para',['for/in order to','prep']],
  ['por',['for/by/through','prep']],['según',['according to','prep']],
  ['sin',['without','prep']],['sobre',['on/about','prep']],['tras',['after/behind','prep']],

// ── Conjunctions ──────────────────────────────────────────────────────────────
  ['y',['and','conj']],['e',['and','conj']],['o',['or','conj']],['u',['or','conj']],
  ['ni',['nor','conj']],['pero',['but','conj']],['sino',['but rather','conj']],
  ['aunque',['although','conj']],['porque',['because','conj']],
  ['pues',['since/so','conj']],['como',['as/like','conj']],
  ['cuando',['when','conj']],['si',['if','conj']],['que',['that','conj']],
  ['mientras',['while','conj']],

// ── Adverbs ───────────────────────────────────────────────────────────────────
  ['no',['no/not','adv']],['sí',['yes','adv']],['también',['also/too','adv']],
  ['tampoco',['neither','adv']],['ya',['already/now','adv']],
  ['aún',['still/yet','adv']],['todavía',['still/yet','adv']],
  ['siempre',['always','adv']],['nunca',['never','adv']],['jamás',['never','adv']],
  ['muy',['very','adv']],['más',['more','adv']],['menos',['less','adv']],
  ['tan',['so/as','adv']],['tanto',['so much','adv']],
  ['bien',['well','adv']],['mal',['badly','adv']],
  ['aquí',['here','adv']],['acá',['here','adv']],['ahí',['there','adv']],
  ['allí',['there','adv']],['allá',['over there','adv']],
  ['arriba',['up/above','adv']],['abajo',['down/below','adv']],
  ['adelante',['forward','adv']],['atrás',['back/behind','adv']],
  ['afuera',['outside','adv']],['adentro',['inside','adv']],
  ['cerca',['near','adv']],['lejos',['far','adv']],
  ['ahora',['now','adv']],['hoy',['today','adv']],['ayer',['yesterday','adv']],
  ['mañana',['tomorrow','adv']],['tarde',['late','adv']],['temprano',['early','adv']],
  ['pronto',['soon','adv']],['después',['after/later','adv']],['antes',['before','adv']],
  ['luego',['then/later','adv']],['rápido',['quickly','adv']],['despacio',['slowly','adv']],
  ['solo',['alone/only','adv']],['sólo',['only','adv']],['juntos',['together','adv']],
  ['apenas',['barely','adv']],['quizás',['maybe','adv']],['quizá',['maybe','adv']],
  ['acaso',['perhaps','adv']],['así',['like this/so','adv']],
  ['cómo',['how','adv']],['cuándo',['when','adv']],['dónde',['where','adv']],
  ['cuánto',['how much','adv']],['cuántos',['how many','adv']],

// ── ser ───────────────────────────────────────────────────────────────────────
  ['ser',['to be','verb']],
  ['soy',['I am','verb']],['eres',['you are','verb']],['es',['is','verb']],
  ['somos',['we are','verb']],['son',['they are','verb']],
  ['era',['was/were','verb']],['eras',['you were','verb']],['éramos',['we were','verb']],
  ['eran',['they were','verb']],
  ['fui',['I was','verb']],['fue',['was','verb']],['fuimos',['we were','verb']],
  ['fueron',['they were','verb']],['fuiste',['you were','verb']],
  ['sido',['been','verb']],['siendo',['being','verb']],
  ['será',['will be','verb']],['sería',['would be','verb']],
  ['sea',['be (subjunctive)','verb']],

// ── estar ─────────────────────────────────────────────────────────────────────
  ['estar',['to be','verb']],
  ['estoy',['I am','verb']],['estás',['you are','verb']],['está',['is','verb']],
  ['estamos',['we are','verb']],['están',['they are','verb']],
  ['estaba',['was','verb']],['estabas',['you were','verb']],
  ['estábamos',['we were','verb']],['estaban',['they were','verb']],
  ['estuve',['I was','verb']],['estuvo',['was','verb']],
  ['estuvimos',['we were','verb']],['estuvieron',['they were','verb']],
  ['estado',['been','verb']],['estando',['being','verb']],
  ['estará',['will be','verb']],['estaría',['would be','verb']],
  ['esté',['be (subjunctive)','verb']],

// ── haber ─────────────────────────────────────────────────────────────────────
  ['haber',['to have (auxiliary)','verb']],
  ['he',['I have','verb']],['has',['you have','verb']],['ha',['has','verb']],
  ['hemos',['we have','verb']],['han',['they have','verb']],
  ['había',['there was/had','verb']],['habían',['they had','verb']],
  ['hubo',['there was','verb']],['hay',['there is/are','verb']],
  ['habrá',['there will be','verb']],['habría',['there would be','verb']],
  ['haya',['have (subjunctive)','verb']],['hubiera',['had (subjunctive)','verb']],

// ── tener ─────────────────────────────────────────────────────────────────────
  ['tener',['to have','verb']],
  ['tengo',['I have','verb']],['tienes',['you have','verb']],['tiene',['has','verb']],
  ['tenemos',['we have','verb']],['tienen',['they have','verb']],
  ['tenía',['had','verb']],['teníamos',['we had','verb']],['tenían',['they had','verb']],
  ['tuve',['I had','verb']],['tuvo',['had','verb']],
  ['tuvimos',['we had','verb']],['tuvieron',['they had','verb']],
  ['tendrá',['will have','verb']],['tendría',['would have','verb']],
  ['tenido',['had','verb']],['teniendo',['having','verb']],
  ['tenga',['have (subjunctive)','verb']],

// ── hacer ─────────────────────────────────────────────────────────────────────
  ['hacer',['to do/make','verb']],
  ['hago',['I do/make','verb']],['haces',['you do','verb']],['hace',['does/makes','verb']],
  ['hacemos',['we do/make','verb']],['hacen',['they do/make','verb']],
  ['hacía',['did/made','verb']],['hacían',['they did','verb']],
  ['hice',['I did/made','verb']],['hizo',['did/made','verb']],
  ['hicimos',['we did','verb']],['hicieron',['they did','verb']],
  ['hará',['will do','verb']],['haría',['would do','verb']],
  ['hecho',['done/made','verb']],['haciendo',['doing/making','verb']],
  ['haga',['do (subjunctive)','verb']],

// ── ir ────────────────────────────────────────────────────────────────────────
  ['ir',['to go','verb']],
  ['voy',['I go','verb']],['vas',['you go','verb']],['va',['goes','verb']],
  ['vamos',["we go/let's go",'verb']],['van',['they go','verb']],
  ['iba',['was going','verb']],['ibas',['you were going','verb']],
  ['íbamos',['we were going','verb']],['iban',['they were going','verb']],
  ['yendo',['going','verb']],['vaya',['go (subjunctive)','verb']],

// ── poder ─────────────────────────────────────────────────────────────────────
  ['poder',['to be able to/can','verb']],
  ['puedo',['I can','verb']],['puedes',['you can','verb']],['puede',['can','verb']],
  ['podemos',['we can','verb']],['pueden',['they can','verb']],
  ['podía',['could','verb']],['podíamos',['we could','verb']],['podían',['they could','verb']],
  ['pude',['I could','verb']],['pudo',['could','verb']],
  ['pudimos',['we could','verb']],['pudieron',['they could','verb']],
  ['podrá',['will be able to','verb']],['podría',['could/would','verb']],
  ['podido',['been able to','verb']],['pudiendo',['being able to','verb']],
  ['pueda',['can (subjunctive)','verb']],

// ── querer ────────────────────────────────────────────────────────────────────
  ['querer',['to want/love','verb']],
  ['quiero',['I want/love','verb']],['quieres',['you want','verb']],
  ['quiere',['wants/loves','verb']],['queremos',['we want','verb']],
  ['quieren',['they want','verb']],
  ['quería',['wanted','verb']],['queríamos',['we wanted','verb']],['querían',['they wanted','verb']],
  ['quise',['I wanted','verb']],['quiso',['wanted','verb']],
  ['querido',['wanted/dear','verb']],['queriendo',['wanting','verb']],
  ['quiera',['want (subjunctive)','verb']],

// ── decir ─────────────────────────────────────────────────────────────────────
  ['decir',['to say/tell','verb']],
  ['digo',['I say','verb']],['dices',['you say','verb']],['dice',['says','verb']],
  ['decimos',['we say','verb']],['dicen',['they say','verb']],
  ['decía',['said','verb']],['decíamos',['we said','verb']],['decían',['they said','verb']],
  ['dije',['I said','verb']],['dijiste',['you said','verb']],['dijo',['said','verb']],
  ['dijimos',['we said','verb']],['dijeron',['they said','verb']],
  ['dirá',['will say','verb']],['diría',['would say','verb']],
  ['dicho',['said','verb']],['diciendo',['saying','verb']],
  ['diga',['say (subjunctive)','verb']],

// ── ver ───────────────────────────────────────────────────────────────────────
  ['ver',['to see','verb']],
  ['veo',['I see','verb']],['ves',['you see','verb']],
  ['vemos',['we see','verb']],['ven',['they see','verb']],
  ['veía',['saw','verb']],['veíamos',['we saw','verb']],['veían',['they saw','verb']],
  ['vi',['I saw','verb']],['viste',['you saw','verb']],['vio',['saw','verb']],
  ['vimos',['we saw','verb']],['vieron',['they saw','verb']],
  ['verá',['will see','verb']],['vería',['would see','verb']],
  ['visto',['seen','verb']],['viendo',['seeing','verb']],

// ── dar ───────────────────────────────────────────────────────────────────────
  ['dar',['to give','verb']],
  ['doy',['I give','verb']],['das',['you give','verb']],['da',['gives','verb']],
  ['damos',['we give','verb']],['dan',['they give','verb']],
  ['daba',['gave','verb']],['daban',['they gave','verb']],
  ['di',['I gave','verb']],['diste',['you gave','verb']],['dio',['gave','verb']],
  ['dimos',['we gave','verb']],['dieron',['they gave','verb']],
  ['dado',['given','verb']],['dando',['giving','verb']],

// ── saber ─────────────────────────────────────────────────────────────────────
  ['saber',['to know','verb']],
  ['sabes',['you know','verb']],['sabe',['knows','verb']],
  ['sabemos',['we know','verb']],['saben',['they know','verb']],
  ['sabía',['knew','verb']],['sabíamos',['we knew','verb']],['sabían',['they knew','verb']],
  ['supe',['I found out','verb']],['supo',['found out','verb']],
  ['supimos',['we found out','verb']],['supieron',['they found out','verb']],
  ['sabido',['known','verb']],['sabiendo',['knowing','verb']],
  ['sepa',['know (subjunctive)','verb']],

// ── venir ─────────────────────────────────────────────────────────────────────
  ['venir',['to come','verb']],
  ['vengo',['I come','verb']],['vienes',['you come','verb']],['viene',['comes','verb']],
  ['venimos',['we come','verb']],['vienen',['they come','verb']],
  ['venía',['was coming','verb']],['venían',['they were coming','verb']],
  ['vine',['I came','verb']],['viniste',['you came','verb']],['vino',['came','verb']],
  ['vinimos',['we came','verb']],['vinieron',['they came','verb']],
  ['vendrá',['will come','verb']],['vendría',['would come','verb']],
  ['venido',['come','verb']],['viniendo',['coming','verb']],
  ['venga',['come (subjunctive)','verb']],

// ── poner ─────────────────────────────────────────────────────────────────────
  ['poner',['to put/place','verb']],
  ['pongo',['I put','verb']],['pones',['you put','verb']],['pone',['puts','verb']],
  ['ponemos',['we put','verb']],['ponen',['they put','verb']],
  ['ponía',['was putting','verb']],['ponían',['they were putting','verb']],
  ['puse',['I put','verb']],['pusiste',['you put','verb']],['puso',['put','verb']],
  ['pusimos',['we put','verb']],['pusieron',['they put','verb']],
  ['pondrá',['will put','verb']],['pondría',['would put','verb']],
  ['puesto',['put','verb']],['poniendo',['putting','verb']],

// ── salir ─────────────────────────────────────────────────────────────────────
  ['salir',['to leave/go out','verb']],
  ['salgo',['I leave','verb']],['sales',['you leave','verb']],['sale',['leaves','verb']],
  ['salimos',['we leave','verb']],['salen',['they leave','verb']],
  ['salía',['was leaving','verb']],['salían',['they were leaving','verb']],
  ['salí',['I left','verb']],['saliste',['you left','verb']],['salió',['left','verb']],
  ['salieron',['they left','verb']],
  ['saldrá',['will leave','verb']],['saldría',['would leave','verb']],
  ['salido',['left','verb']],['saliendo',['leaving','verb']],

// ── vivir ─────────────────────────────────────────────────────────────────────
  ['vivir',['to live','verb']],
  ['vivo',['I live','verb']],['vives',['you live','verb']],['vive',['lives','verb']],
  ['vivimos',['we live','verb']],['viven',['they live','verb']],
  ['vivía',['lived','verb']],['vivíamos',['we lived','verb']],['vivían',['they lived','verb']],
  ['viví',['I lived','verb']],['viviste',['you lived','verb']],['vivió',['lived','verb']],
  ['vivieron',['they lived','verb']],
  ['vivido',['lived','verb']],['viviendo',['living','verb']],

// ── conocer ───────────────────────────────────────────────────────────────────
  ['conocer',['to know/meet','verb']],
  ['conozco',['I know','verb']],['conoces',['you know','verb']],['conoce',['knows','verb']],
  ['conocemos',['we know','verb']],['conocen',['they know','verb']],
  ['conocía',['knew','verb']],['conocían',['they knew','verb']],
  ['conocí',['I met','verb']],['conociste',['you met','verb']],['conoció',['met','verb']],
  ['conocieron',['they met','verb']],
  ['conocido',['known/met','verb']],['conociendo',['knowing','verb']],

// ── hablar ────────────────────────────────────────────────────────────────────
  ['hablar',['to speak/talk','verb']],
  ['hablo',['I speak','verb']],['hablas',['you speak','verb']],['habla',['speaks','verb']],
  ['hablamos',['we speak','verb']],['hablan',['they speak','verb']],
  ['hablaba',['spoke','verb']],['hablaban',['they spoke','verb']],
  ['hablé',['I spoke','verb']],['hablaste',['you spoke','verb']],['habló',['spoke','verb']],
  ['hablaron',['they spoke','verb']],
  ['hablado',['spoken','verb']],['hablando',['speaking','verb']],

// ── llevar ────────────────────────────────────────────────────────────────────
  ['llevar',['to carry/take/wear','verb']],
  ['llevo',['I carry/wear','verb']],['llevas',['you carry','verb']],
  ['lleva',['carries/wears','verb']],['llevamos',['we carry','verb']],
  ['llevan',['they carry','verb']],
  ['llevaba',['was carrying','verb']],['llevaban',['they carried','verb']],
  ['llevé',['I carried','verb']],['llevó',['carried','verb']],['llevaron',['they carried','verb']],
  ['llevado',['carried','verb']],['llevando',['carrying','verb']],

// ── pasar ─────────────────────────────────────────────────────────────────────
  ['pasar',['to pass/happen','verb']],
  ['paso',['step/I pass','noun']],['pasas',['you pass','verb']],['pasa',['passes/happens','verb']],
  ['pasamos',['we pass','verb']],['pasan',['they pass','verb']],
  ['pasaba',['was passing','verb']],['pasaban',['they passed','verb']],
  ['pasé',['I passed','verb']],['pasaste',['you passed','verb']],['pasó',['passed/happened','verb']],
  ['pasaron',['they passed','verb']],
  ['pasado',['past/passed','adj']],['pasando',['passing','verb']],

// ── llegar ────────────────────────────────────────────────────────────────────
  ['llegar',['to arrive','verb']],
  ['llego',['I arrive','verb']],['llegas',['you arrive','verb']],['llega',['arrives','verb']],
  ['llegamos',['we arrive','verb']],['llegan',['they arrive','verb']],
  ['llegaba',['was arriving','verb']],['llegaban',['they arrived','verb']],
  ['llegué',['I arrived','verb']],['llegaste',['you arrived','verb']],['llegó',['arrived','verb']],
  ['llegaron',['they arrived','verb']],
  ['llegado',['arrived','verb']],['llegando',['arriving','verb']],

// ── seguir ────────────────────────────────────────────────────────────────────
  ['seguir',['to follow/continue','verb']],
  ['sigo',['I follow','verb']],['sigues',['you follow','verb']],['sigue',['follows','verb']],
  ['seguimos',['we follow','verb']],['siguen',['they follow','verb']],
  ['seguía',['was following','verb']],['seguían',['they followed','verb']],
  ['siguió',['followed','verb']],['siguieron',['they followed','verb']],
  ['seguido',['followed','verb']],['siguiendo',['following','verb']],

// ── encontrar ─────────────────────────────────────────────────────────────────
  ['encontrar',['to find/meet','verb']],
  ['encuentro',['I find','verb']],['encuentras',['you find','verb']],
  ['encuentra',['finds','verb']],['encontramos',['we find','verb']],
  ['encuentran',['they find','verb']],
  ['encontré',['I found','verb']],['encontró',['found','verb']],
  ['encontraron',['they found','verb']],
  ['encontrado',['found','verb']],['encontrando',['finding','verb']],

// ── creer ─────────────────────────────────────────────────────────────────────
  ['creer',['to believe/think','verb']],
  ['creo',['I believe/think','verb']],['crees',['you believe','verb']],
  ['cree',['believes','verb']],['creemos',['we believe','verb']],
  ['creen',['they believe','verb']],
  ['creía',['believed','verb']],['creían',['they believed','verb']],
  ['creí',['I believed','verb']],['creyó',['believed','verb']],
  ['creyeron',['they believed','verb']],
  ['creído',['believed','verb']],['creyendo',['believing','verb']],

// ── trabajar ──────────────────────────────────────────────────────────────────
  ['trabajar',['to work','verb']],
  ['trabajo',['I work / job','noun']],['trabajas',['you work','verb']],
  ['trabaja',['works','verb']],['trabajamos',['we work','verb']],
  ['trabajan',['they work','verb']],
  ['trabajé',['I worked','verb']],['trabajó',['worked','verb']],
  ['trabajaron',['they worked','verb']],
  ['trabajado',['worked','verb']],['trabajando',['working','verb']],

// ── other high-frequency verbs ────────────────────────────────────────────────
  ['comer',['to eat','verb']],
  ['como',['I eat','verb']],['comes',['you eat','verb']],['come',['eats','verb']],
  ['comemos',['we eat','verb']],['comen',['they eat','verb']],
  ['comía',['ate','verb']],['comí',['I ate','verb']],['comió',['ate','verb']],
  ['comieron',['they ate','verb']],['comido',['eaten','verb']],['comiendo',['eating','verb']],

  ['beber',['to drink','verb']],
  ['bebo',['I drink','verb']],['bebes',['you drink','verb']],['bebe',['drinks','verb']],
  ['bebemos',['we drink','verb']],['beben',['they drink','verb']],
  ['bebí',['I drank','verb']],['bebió',['drank','verb']],
  ['bebido',['drunk','verb']],['bebiendo',['drinking','verb']],

  ['dormir',['to sleep','verb']],
  ['duermo',['I sleep','verb']],['duermes',['you sleep','verb']],['duerme',['sleeps','verb']],
  ['dormimos',['we sleep','verb']],['duermen',['they sleep','verb']],
  ['dormí',['I slept','verb']],['durmió',['slept','verb']],['durmieron',['they slept','verb']],
  ['dormido',['asleep/slept','verb']],['durmiendo',['sleeping','verb']],

  ['caminar',['to walk','verb']],
  ['camino',['path/road','noun']],['caminas',['you walk','verb']],
  ['camina',['walks','verb']],['caminamos',['we walk','verb']],['caminan',['they walk','verb']],
  ['caminó',['walked','verb']],['caminando',['walking','verb']],

  ['correr',['to run','verb']],
  ['corro',['I run','verb']],['corres',['you run','verb']],['corre',['runs','verb']],
  ['corremos',['we run','verb']],['corren',['they run','verb']],
  ['corrió',['ran','verb']],['corriendo',['running','verb']],

  ['escribir',['to write','verb']],
  ['escribo',['I write','verb']],['escribes',['you write','verb']],
  ['escribe',['writes','verb']],['escribimos',['we write','verb']],['escriben',['they write','verb']],
  ['escribí',['I wrote','verb']],['escribió',['wrote','verb']],
  ['escrito',['written','verb']],['escribiendo',['writing','verb']],

  ['leer',['to read','verb']],
  ['leo',['I read','verb']],['lees',['you read','verb']],['lee',['reads','verb']],
  ['leemos',['we read','verb']],['leen',['they read','verb']],
  ['leí',['I read','verb']],['leyó',['read','verb']],['leyeron',['they read','verb']],
  ['leído',['read','verb']],['leyendo',['reading','verb']],

  ['pensar',['to think','verb']],
  ['pienso',['I think','verb']],['piensas',['you think','verb']],['piensa',['thinks','verb']],
  ['pensamos',['we think','verb']],['piensan',['they think','verb']],
  ['pensaba',['thought','verb']],['pensé',['I thought','verb']],['pensó',['thought','verb']],
  ['pensaron',['they thought','verb']],
  ['pensado',['thought','verb']],['pensando',['thinking','verb']],

  ['sentir',['to feel','verb']],
  ['siento',['I feel','verb']],['sientes',['you feel','verb']],['siente',['feels','verb']],
  ['sentimos',['we feel','verb']],['sienten',['they feel','verb']],
  ['sentía',['felt','verb']],['sentí',['I felt','verb']],['sintió',['felt','verb']],
  ['sintieron',['they felt','verb']],['sintiendo',['feeling','verb']],

  ['mirar',['to look/watch','verb']],
  ['miro',['I look','verb']],['miras',['you look','verb']],['mira',['looks','verb']],
  ['miramos',['we look','verb']],['miran',['they look','verb']],
  ['miré',['I looked','verb']],['miró',['looked','verb']],['miraron',['they looked','verb']],
  ['mirado',['looked','verb']],['mirando',['looking','verb']],

  ['escuchar',['to listen/hear','verb']],
  ['escucho',['I listen','verb']],['escuchas',['you listen','verb']],
  ['escucha',['listens','verb']],['escuchamos',['we listen','verb']],
  ['escuchan',['they listen','verb']],
  ['escuché',['I listened','verb']],['escuchó',['listened','verb']],
  ['escucharon',['they listened','verb']],
  ['escuchado',['heard','verb']],['escuchando',['listening','verb']],

  ['comprar',['to buy','verb']],
  ['compro',['I buy','verb']],['compras',['you buy','verb']],['compra',['buys','verb']],
  ['compramos',['we buy','verb']],['compran',['they buy','verb']],
  ['compré',['I bought','verb']],['compró',['bought','verb']],['compraron',['they bought','verb']],
  ['comprado',['bought','verb']],['comprando',['buying','verb']],

  ['vender',['to sell','verb']],
  ['vendo',['I sell','verb']],['vendes',['you sell','verb']],['vende',['sells','verb']],
  ['vendemos',['we sell','verb']],['venden',['they sell','verb']],
  ['vendí',['I sold','verb']],['vendió',['sold','verb']],['vendieron',['they sold','verb']],
  ['vendido',['sold','verb']],['vendiendo',['selling','verb']],

  ['pedir',['to ask for/order','verb']],
  ['pido',['I ask for','verb']],['pides',['you ask for','verb']],['pide',['asks for','verb']],
  ['pedimos',['we ask for','verb']],['piden',['they ask for','verb']],
  ['pedí',['I asked for','verb']],['pidió',['asked for','verb']],['pidieron',['they asked for','verb']],
  ['pedido',['request/order','noun']],['pidiendo',['asking for','verb']],

  ['esperar',['to wait/hope','verb']],
  ['espero',['I wait/hope','verb']],['esperas',['you wait','verb']],
  ['espera',['waits/hopes','verb']],['esperamos',['we wait','verb']],
  ['esperan',['they wait','verb']],
  ['esperé',['I waited','verb']],['esperó',['waited','verb']],['esperaron',['they waited','verb']],
  ['esperado',['expected','verb']],['esperando',['waiting','verb']],

  ['empezar',['to begin/start','verb']],
  ['empiezo',['I begin','verb']],['empiezas',['you begin','verb']],
  ['empieza',['begins','verb']],['empezamos',['we begin','verb']],
  ['empiezan',['they begin','verb']],
  ['empecé',['I began','verb']],['empezó',['began','verb']],['empezaron',['they began','verb']],
  ['empezado',['begun','verb']],['empezando',['beginning','verb']],

  ['terminar',['to finish/end','verb']],
  ['termino',['I finish','verb']],['terminas',['you finish','verb']],
  ['termina',['finishes','verb']],['terminamos',['we finish','verb']],
  ['terminan',['they finish','verb']],
  ['terminé',['I finished','verb']],['terminó',['finished','verb']],
  ['terminaron',['they finished','verb']],
  ['terminado',['finished','adj']],['terminando',['finishing','verb']],

  ['necesitar',['to need','verb']],
  ['necesito',['I need','verb']],['necesitas',['you need','verb']],
  ['necesita',['needs','verb']],['necesitamos',['we need','verb']],
  ['necesitan',['they need','verb']],
  ['necesitó',['needed','verb']],['necesitaron',['they needed','verb']],
  ['necesitado',['needed','verb']],['necesitando',['needing','verb']],

  ['usar',['to use','verb']],
  ['uso',['I use/use','noun']],['usas',['you use','verb']],['usa',['uses','verb']],
  ['usamos',['we use','verb']],['usan',['they use','verb']],
  ['usé',['I used','verb']],['usó',['used','verb']],
  ['usado',['used','adj']],['usando',['using','verb']],

  ['recordar',['to remember','verb']],
  ['recuerdo',['I remember/memory','noun']],['recuerdas',['you remember','verb']],
  ['recuerda',['remembers','verb']],['recordamos',['we remember','verb']],
  ['recuerdan',['they remember','verb']],
  ['recordé',['I remembered','verb']],['recordó',['remembered','verb']],
  ['recordado',['remembered','verb']],['recordando',['remembering','verb']],

  ['entender',['to understand','verb']],
  ['entiendo',['I understand','verb']],['entiendes',['you understand','verb']],
  ['entiende',['understands','verb']],['entendemos',['we understand','verb']],
  ['entienden',['they understand','verb']],
  ['entendí',['I understood','verb']],['entendió',['understood','verb']],
  ['entendieron',['they understood','verb']],
  ['entendido',['understood','verb']],['entendiendo',['understanding','verb']],

  ['ganar',['to win/earn','verb']],
  ['gano',['I win','verb']],['ganas',['you win','verb']],['gana',['wins','verb']],
  ['ganamos',['we win','verb']],['ganan',['they win','verb']],
  ['gané',['I won','verb']],['ganó',['won','verb']],['ganaron',['they won','verb']],
  ['ganado',['won','verb']],['ganando',['winning','verb']],

  ['perder',['to lose','verb']],
  ['pierdo',['I lose','verb']],['pierdes',['you lose','verb']],['pierde',['loses','verb']],
  ['perdemos',['we lose','verb']],['pierden',['they lose','verb']],
  ['perdí',['I lost','verb']],['perdiste',['you lost','verb']],['perdió',['lost','verb']],
  ['perdieron',['they lost','verb']],
  ['perdido',['lost','adj']],['perdiendo',['losing','verb']],

  ['abrir',['to open','verb']],
  ['abro',['I open','verb']],['abres',['you open','verb']],['abre',['opens','verb']],
  ['abrimos',['we open','verb']],['abren',['they open','verb']],
  ['abrí',['I opened','verb']],['abrió',['opened','verb']],['abrieron',['they opened','verb']],
  ['abierto',['open/opened','adj']],['abriendo',['opening','verb']],

  ['cerrar',['to close','verb']],
  ['cierro',['I close','verb']],['cierras',['you close','verb']],['cierra',['closes','verb']],
  ['cerramos',['we close','verb']],['cierran',['they close','verb']],
  ['cerré',['I closed','verb']],['cerró',['closed','verb']],['cerraron',['they closed','verb']],
  ['cerrado',['closed','adj']],['cerrando',['closing','verb']],

  ['jugar',['to play','verb']],
  ['juego',['I play/game','noun']],['juegas',['you play','verb']],['juega',['plays','verb']],
  ['jugamos',['we play','verb']],['juegan',['they play','verb']],
  ['jugué',['I played','verb']],['jugó',['played','verb']],['jugaron',['they played','verb']],
  ['jugado',['played','verb']],['jugando',['playing','verb']],

  ['ayudar',['to help','verb']],
  ['ayudo',['I help','verb']],['ayudas',['you help','verb']],['ayuda',['helps/help','noun']],
  ['ayudamos',['we help','verb']],['ayudan',['they help','verb']],
  ['ayudé',['I helped','verb']],['ayudó',['helped','verb']],['ayudaron',['they helped','verb']],
  ['ayudado',['helped','verb']],['ayudando',['helping','verb']],

  ['mostrar',['to show','verb']],
  ['muestro',['I show','verb']],['muestras',['you show','verb']],['muestra',['shows/sample','noun']],
  ['mostramos',['we show','verb']],['muestran',['they show','verb']],
  ['mostré',['I showed','verb']],['mostró',['showed','verb']],
  ['mostrado',['shown','verb']],['mostrando',['showing','verb']],

  ['cambiar',['to change','verb']],
  ['cambio',['I change/change','noun']],['cambias',['you change','verb']],
  ['cambia',['changes','verb']],['cambiamos',['we change','verb']],
  ['cambian',['they change','verb']],
  ['cambié',['I changed','verb']],['cambió',['changed','verb']],
  ['cambiado',['changed','verb']],['cambiando',['changing','verb']],

  ['crear',['to create','verb']],
  ['creo',['I create','verb']],['creas',['you create','verb']],
  ['crea',['creates','verb']],['creamos',['we create','verb']],['crean',['they create','verb']],
  ['creé',['I created','verb']],['creó',['created','verb']],['crearon',['they created','verb']],
  ['creado',['created','verb']],['creando',['creating','verb']],

  ['contar',['to count/tell','verb']],
  ['cuento',['I count/story','noun']],['cuentas',['you count','verb']],
  ['cuenta',['counts/account','noun']],['contamos',['we count','verb']],
  ['cuentan',['they count','verb']],
  ['conté',['I counted','verb']],['contó',['counted/told','verb']],
  ['contaron',['they counted','verb']],
  ['contado',['counted/told','verb']],['contando',['counting','verb']],

// ── People & relationships ─────────────────────────────────────────────────────
  ['persona',['person','noun']],['personas',['people','noun']],['gente',['people','noun']],
  ['hombre',['man','noun']],['hombres',['men','noun']],
  ['mujer',['woman','noun']],['mujeres',['women','noun']],
  ['niño',['boy/child','noun']],['niña',['girl','noun']],
  ['niños',['children','noun']],['niñas',['girls','noun']],
  ['chico',['boy/guy','noun']],['chica',['girl','noun']],
  ['joven',['young person','noun']],['jóvenes',['young people','noun']],
  ['adulto',['adult','noun']],['anciano',['elderly man','noun']],['bebé',['baby','noun']],
  ['amigo',['friend','noun']],['amiga',['friend (f)','noun']],['amigos',['friends','noun']],
  ['enemigo',['enemy','noun']],
  ['compañero',['partner/companion','noun']],['compañera',['partner/companion (f)','noun']],
  ['vecino',['neighbor','noun']],['vecina',['neighbor (f)','noun']],
  ['ciudadano',['citizen','noun']],

// ── Family ────────────────────────────────────────────────────────────────────
  ['familia',['family','noun']],
  ['padre',['father','noun']],['madre',['mother','noun']],['padres',['parents','noun']],
  ['hijo',['son','noun']],['hija',['daughter','noun']],['hijos',['children/sons','noun']],
  ['hermano',['brother','noun']],['hermana',['sister','noun']],['hermanos',['siblings','noun']],
  ['abuelo',['grandfather','noun']],['abuela',['grandmother','noun']],['abuelos',['grandparents','noun']],
  ['nieto',['grandson','noun']],['nieta',['granddaughter','noun']],
  ['tío',['uncle','noun']],['tía',['aunt','noun']],
  ['primo',['cousin','noun']],['prima',['cousin (f)','noun']],
  ['esposo',['husband','noun']],['esposa',['wife','noun']],['marido',['husband','noun']],
  ['novio',['boyfriend','noun']],['novia',['girlfriend','noun']],
  ['pareja',['partner/couple','noun']],

// ── Body ──────────────────────────────────────────────────────────────────────
  ['cuerpo',['body','noun']],['cabeza',['head','noun']],['cara',['face','noun']],
  ['ojo',['eye','noun']],['ojos',['eyes','noun']],['nariz',['nose','noun']],
  ['boca',['mouth','noun']],['oreja',['ear','noun']],['orejas',['ears','noun']],
  ['pelo',['hair','noun']],['cabello',['hair','noun']],['cuello',['neck','noun']],
  ['hombro',['shoulder','noun']],['brazo',['arm','noun']],['brazos',['arms','noun']],
  ['mano',['hand','noun']],['manos',['hands','noun']],
  ['dedo',['finger/toe','noun']],['dedos',['fingers','noun']],
  ['pecho',['chest','noun']],['espalda',['back','noun']],['estómago',['stomach','noun']],
  ['pierna',['leg','noun']],['piernas',['legs','noun']],
  ['rodilla',['knee','noun']],['pie',['foot','noun']],['pies',['feet','noun']],
  ['corazón',['heart','noun']],['sangre',['blood','noun']],
  ['hueso',['bone','noun']],['piel',['skin','noun']],

// ── Places ────────────────────────────────────────────────────────────────────
  ['lugar',['place','noun']],['lugares',['places','noun']],
  ['ciudad',['city','noun']],['ciudades',['cities','noun']],
  ['pueblo',['town/village','noun']],['país',['country','noun']],['países',['countries','noun']],
  ['mundo',['world','noun']],['tierra',['earth/land','noun']],
  ['casa',['house/home','noun']],['casas',['houses','noun']],['hogar',['home','noun']],
  ['edificio',['building','noun']],['habitación',['room','noun']],['cuarto',['room','noun']],
  ['calle',['street','noun']],['calles',['streets','noun']],
  ['camino',['road/path','noun']],['avenida',['avenue','noun']],
  ['escuela',['school','noun']],['colegio',['school','noun']],
  ['universidad',['university','noun']],['hospital',['hospital','noun']],
  ['iglesia',['church','noun']],['tienda',['store','noun']],['mercado',['market','noun']],
  ['restaurante',['restaurant','noun']],['banco',['bank','noun']],
  ['oficina',['office','noun']],['empresa',['company','noun']],
  ['gobierno',['government','noun']],['parque',['park','noun']],
  ['playa',['beach','noun']],['montaña',['mountain','noun']],
  ['río',['river','noun']],['mar',['sea','noun']],
  ['océano',['ocean','noun']],['lago',['lake','noun']],
  ['bosque',['forest','noun']],['campo',['field/countryside','noun']],
  ['norte',['north','noun']],['sur',['south','noun']],
  ['este',['east','noun']],['oeste',['west','noun']],

// ── Time ──────────────────────────────────────────────────────────────────────
  ['tiempo',['time/weather','noun']],
  ['hora',['hour/time','noun']],['horas',['hours','noun']],
  ['minuto',['minute','noun']],['minutos',['minutes','noun']],
  ['segundo',['second','noun']],
  ['día',['day','noun']],['días',['days','noun']],
  ['semana',['week','noun']],['semanas',['weeks','noun']],
  ['mes',['month','noun']],['meses',['months','noun']],
  ['año',['year','noun']],['años',['years','noun']],
  ['siglo',['century','noun']],
  ['momento',['moment','noun']],['vez',['time/occasion','noun']],['veces',['times','noun']],
  ['rato',['while/moment','noun']],

// ── Days ──────────────────────────────────────────────────────────────────────
  ['lunes',['Monday','noun']],['martes',['Tuesday','noun']],
  ['miércoles',['Wednesday','noun']],['jueves',['Thursday','noun']],
  ['viernes',['Friday','noun']],['sábado',['Saturday','noun']],['domingo',['Sunday','noun']],

// ── Months ────────────────────────────────────────────────────────────────────
  ['enero',['January','noun']],['febrero',['February','noun']],['marzo',['March','noun']],
  ['abril',['April','noun']],['mayo',['May','noun']],['junio',['June','noun']],
  ['julio',['July','noun']],['agosto',['August','noun']],['septiembre',['September','noun']],
  ['octubre',['October','noun']],['noviembre',['November','noun']],['diciembre',['December','noun']],

// ── Seasons ───────────────────────────────────────────────────────────────────
  ['primavera',['spring','noun']],['verano',['summer','noun']],
  ['otoño',['autumn/fall','noun']],['invierno',['winter','noun']],

// ── Numbers ───────────────────────────────────────────────────────────────────
  ['cero',['zero','num']],['uno',['one','num']],['dos',['two','num']],
  ['tres',['three','num']],['cuatro',['four','num']],['cinco',['five','num']],
  ['seis',['six','num']],['siete',['seven','num']],['ocho',['eight','num']],
  ['nueve',['nine','num']],['diez',['ten','num']],['once',['eleven','num']],
  ['doce',['twelve','num']],['trece',['thirteen','num']],['catorce',['fourteen','num']],
  ['quince',['fifteen','num']],['veinte',['twenty','num']],['treinta',['thirty','num']],
  ['cuarenta',['forty','num']],['cincuenta',['fifty','num']],
  ['sesenta',['sixty','num']],['setenta',['seventy','num']],
  ['ochenta',['eighty','num']],['noventa',['ninety','num']],
  ['cien',['one hundred','num']],['ciento',['one hundred','num']],
  ['mil',['one thousand','num']],['millón',['million','num']],
  ['primero',['first','num']],['primera',['first','num']],
  ['último',['last/latest','adj']],['última',['last','adj']],

// ── Food & drink ──────────────────────────────────────────────────────────────
  ['comida',['food/meal','noun']],['bebida',['drink','noun']],
  ['agua',['water','noun']],['pan',['bread','noun']],
  ['carne',['meat','noun']],['pollo',['chicken','noun']],
  ['pescado',['fish (food)','noun']],['arroz',['rice','noun']],
  ['frijoles',['beans','noun']],['frijol',['bean','noun']],
  ['sopa',['soup','noun']],['ensalada',['salad','noun']],
  ['fruta',['fruit','noun']],['verdura',['vegetable','noun']],
  ['manzana',['apple','noun']],['naranja',['orange','noun']],
  ['plátano',['banana','noun']],['tomate',['tomato','noun']],
  ['papa',['potato','noun']],['patata',['potato','noun']],
  ['queso',['cheese','noun']],['huevo',['egg','noun']],['huevos',['eggs','noun']],
  ['leche',['milk','noun']],['café',['coffee','noun']],['té',['tea','noun']],
  ['cerveza',['beer','noun']],['vino',['wine','noun']],
  ['jugo',['juice','noun']],['zumo',['juice','noun']],
  ['sal',['salt','noun']],['azúcar',['sugar','noun']],['aceite',['oil','noun']],
  ['desayuno',['breakfast','noun']],['almuerzo',['lunch','noun']],['cena',['dinner','noun']],

// ── Objects & things ──────────────────────────────────────────────────────────
  ['cosa',['thing','noun']],['cosas',['things','noun']],['objeto',['object','noun']],
  ['libro',['book','noun']],['libros',['books','noun']],
  ['papel',['paper','noun']],['carta',['letter','noun']],
  ['mesa',['table','noun']],['silla',['chair','noun']],['cama',['bed','noun']],
  ['puerta',['door','noun']],['ventana',['window','noun']],
  ['suelo',['floor/ground','noun']],['techo',['ceiling/roof','noun']],['pared',['wall','noun']],
  ['teléfono',['phone','noun']],['celular',['cell phone','noun']],
  ['computadora',['computer','noun']],['ordenador',['computer','noun']],
  ['carro',['car','noun']],['coche',['car','noun']],['auto',['car','noun']],
  ['camión',['truck','noun']],
  ['ropa',['clothes','noun']],['camisa',['shirt','noun']],
  ['pantalón',['pants','noun']],['pantalones',['pants','noun']],
  ['zapato',['shoe','noun']],['zapatos',['shoes','noun']],
  ['dinero',['money','noun']],['precio',['price','noun']],

// ── Abstract & general nouns ──────────────────────────────────────────────────
  ['número',['number','noun']],['números',['numbers','noun']],
  ['nombre',['name','noun']],['nombres',['names','noun']],
  ['palabra',['word','noun']],['palabras',['words','noun']],
  ['idea',['idea','noun']],['pregunta',['question','noun']],
  ['respuesta',['answer/response','noun']],
  ['problema',['problem','noun']],['problemas',['problems','noun']],
  ['solución',['solution','noun']],['información',['information','noun']],
  ['noticia',['news item','noun']],['noticias',['news','noun']],
  ['historia',['history/story','noun']],
  ['parte',['part','noun']],['partes',['parts','noun']],
  ['tipo',['type/kind','noun']],['tipos',['types','noun']],
  ['forma',['form/way','noun']],['formas',['forms/ways','noun']],
  ['manera',['way/manner','noun']],['modo',['way/mode','noun']],
  ['caso',['case','noun']],['casos',['cases','noun']],
  ['punto',['point','noun']],['puntos',['points','noun']],
  ['grupo',['group','noun']],['grupos',['groups','noun']],
  ['sistema',['system','noun']],['proceso',['process','noun']],
  ['resultado',['result','noun']],['resultados',['results','noun']],
  ['nivel',['level','noun']],['ejemplo',['example','noun']],
  ['estado',['state/condition','noun']],['estados',['states','noun']],
  ['poder',['power','noun']],['fuerza',['force/strength','noun']],
  ['vida',['life','noun']],['muerte',['death','noun']],
  ['amor',['love','noun']],['guerra',['war','noun']],['paz',['peace','noun']],
  ['verdad',['truth','noun']],['mentira',['lie','noun']],
  ['razón',['reason','noun']],['ley',['law','noun']],
  ['derecho',['right/law','noun']],['derechos',['rights','noun']],
  ['sociedad',['society','noun']],['cultura',['culture','noun']],
  ['arte',['art','noun']],['música',['music','noun']],
  ['película',['movie/film','noun']],['películas',['movies','noun']],
  ['juego',['game','noun']],['juegos',['games','noun']],
  ['deporte',['sport','noun']],['deportes',['sports','noun']],
  ['fútbol',['soccer','noun']],
  ['ciencia',['science','noun']],['tecnología',['technology','noun']],
  ['naturaleza',['nature','noun']],
  ['animal',['animal','noun']],['animales',['animals','noun']],
  ['perro',['dog','noun']],['gato',['cat','noun']],
  ['pájaro',['bird','noun']],['pez',['fish','noun']],['caballo',['horse','noun']],
  ['sentido',['sense/meaning','noun']],['recuerdo',['memory/souvenir','noun']],

// ── Nature ────────────────────────────────────────────────────────────────────
  ['sol',['sun','noun']],['luna',['moon','noun']],
  ['estrella',['star','noun']],['estrellas',['stars','noun']],
  ['cielo',['sky/heaven','noun']],['nube',['cloud','noun']],['nubes',['clouds','noun']],
  ['lluvia',['rain','noun']],['nieve',['snow','noun']],
  ['viento',['wind','noun']],['fuego',['fire','noun']],
  ['árbol',['tree','noun']],['árboles',['trees','noun']],
  ['flor',['flower','noun']],['flores',['flowers','noun']],

// ── Adjectives ────────────────────────────────────────────────────────────────
  ['bueno',['good','adj']],['buena',['good','adj']],
  ['malo',['bad','adj']],['mala',['bad','adj']],
  ['grande',['big/great','adj']],['grandes',['big/great','adj']],
  ['pequeño',['small','adj']],['pequeña',['small','adj']],
  ['nuevo',['new','adj']],['nueva',['new','adj']],
  ['viejo',['old','adj']],['vieja',['old','adj']],
  ['largo',['long','adj']],['larga',['long','adj']],
  ['corto',['short','adj']],['corta',['short','adj']],
  ['alto',['tall/high','adj']],['alta',['tall/high','adj']],
  ['bajo',['short/low','adj']],['baja',['short/low','adj']],
  ['bonito',['pretty','adj']],['bonita',['pretty','adj']],
  ['lindo',['cute/pretty','adj']],['linda',['cute/pretty','adj']],
  ['feo',['ugly','adj']],['fea',['ugly','adj']],
  ['rico',['rich/delicious','adj']],['rica',['rich/delicious','adj']],
  ['pobre',['poor','adj']],
  ['feliz',['happy','adj']],['triste',['sad','adj']],
  ['contento',['happy/content','adj']],['contenta',['happy/content','adj']],
  ['enojado',['angry','adj']],['enojada',['angry','adj']],
  ['cansado',['tired','adj']],['cansada',['tired','adj']],
  ['enfermo',['sick','adj']],['enferma',['sick','adj']],
  ['sano',['healthy','adj']],['sana',['healthy','adj']],
  ['fuerte',['strong','adj']],['fuertes',['strong','adj']],
  ['débil',['weak','adj']],
  ['rápido',['fast','adj']],['rápida',['fast','adj']],
  ['lento',['slow','adj']],['lenta',['slow','adj']],
  ['difícil',['difficult','adj']],['fácil',['easy','adj']],
  ['importante',['important','adj']],
  ['posible',['possible','adj']],['imposible',['impossible','adj']],
  ['necesario',['necessary','adj']],['necesaria',['necessary','adj']],
  ['diferente',['different','adj']],['diferentes',['different','adj']],
  ['igual',['equal/same','adj']],['libre',['free','adj']],
  ['seguro',['safe/sure','adj']],['segura',['safe/sure','adj']],
  ['verdadero',['true/real','adj']],['verdadera',['true/real','adj']],
  ['falso',['false','adj']],['falsa',['false','adj']],
  ['próximo',['next/near','adj']],['próxima',['next/near','adj']],
  ['siguiente',['next/following','adj']],['anterior',['previous','adj']],
  ['mejor',['better/best','adj']],['peor',['worse/worst','adj']],
  ['mayor',['older/greater','adj']],['menor',['younger/smaller','adj']],
  ['mucho',['much','adj']],['mucha',['much','adj']],
  ['muchos',['many','adj']],['muchas',['many','adj']],
  ['poco',['little','adj']],['poca',['little','adj']],
  ['pocos',['few','adj']],['pocas',['few','adj']],
  ['bastante',['enough/quite','adj']],
  ['demasiado',['too much','adj']],['demasiada',['too much','adj']],
  ['algún',['some/any','adj']],['alguna',['some','adj']],
  ['algunos',['some','adj']],['algunas',['some','adj']],
  ['ningún',['no/none','adj']],['ninguna',['no/none','adj']],
  ['otro',['other/another','adj']],['otra',['other/another','adj']],
  ['otros',['others','adj']],['otras',['others','adj']],
  ['cierto',['certain','adj']],['cierta',['certain','adj']],
  ['varios',['several','adj']],['varias',['several','adj']],
  ['propio',['own','adj']],['propia',['own','adj']],
  ['solo',['alone/only','adj']],['sola',['alone','adj']],
  ['lleno',['full','adj']],['llena',['full','adj']],
  ['vacío',['empty','adj']],['vacía',['empty','adj']],
  ['limpio',['clean','adj']],['limpia',['clean','adj']],
  ['sucio',['dirty','adj']],['sucia',['dirty','adj']],
  ['oscuro',['dark','adj']],['oscura',['dark','adj']],
  ['claro',['clear/light','adj']],['clara',['clear','adj']],
  ['caliente',['hot','adj']],['frío',['cold','adj']],['fría',['cold','adj']],
  ['fresco',['fresh/cool','adj']],['fresca',['fresh/cool','adj']],
  ['tranquilo',['calm/quiet','adj']],['tranquila',['calm','adj']],
  ['alegre',['cheerful/happy','adj']],
  ['hermoso',['beautiful','adj']],['hermosa',['beautiful','adj']],
  ['extraño',['strange/foreign','adj']],['extraña',['strange','adj']],
  ['especial',['special','adj']],['normal',['normal','adj']],
  ['público',['public','adj']],['privado',['private','adj']],['privada',['private','adj']],
  ['nacional',['national','adj']],['internacional',['international','adj']],
  ['político',['political','adj']],['política',['political/politics','noun']],
  ['económico',['economic','adj']],['social',['social','adj']],

// ── Colors ────────────────────────────────────────────────────────────────────
  ['rojo',['red','adj']],['roja',['red','adj']],
  ['azul',['blue','adj']],['verde',['green','adj']],
  ['amarillo',['yellow','adj']],['amarilla',['yellow','adj']],
  ['negro',['black','adj']],['negra',['black','adj']],
  ['blanco',['white','adj']],['blanca',['white','adj']],
  ['gris',['gray','adj']],['naranja',['orange','adj']],
  ['rosa',['pink','adj']],['morado',['purple','adj']],['morada',['purple','adj']],
  ['café',['brown','adj']],['marrón',['brown','adj']],
  ['dorado',['golden','adj']],['plateado',['silver','adj']],

// ── Interjections & common phrases ────────────────────────────────────────────
  ['hola',['hello/hi','int']],['adiós',['goodbye','int']],
  ['gracias',['thank you','int']],['perdón',['excuse me/sorry','int']],
  ['disculpe',['excuse me','int']],['bueno',['okay/well','int']],
  ['vale',['okay','int']],['ojalá',['hopefully','int']],
  ['salud',['cheers/bless you','int']],
  ['bienvenido',['welcome','int']],['bienvenida',['welcome','int']],
  ['felicidades',['congratulations','int']],

// ── Common phrases ────────────────────────────────────────────────────────────
  ['soy de',["I'm from",'phrase']],
  ['eres de',["you're from",'phrase']],
  ['es de',['is from','phrase']],
  ['me llamo',['my name is','phrase']],
  ['te llamas',['your name is','phrase']],
  ['se llama',['his/her name is','phrase']],
  ['cómo estás',['how are you','phrase']],
  ['cómo está',['how are you (formal)','phrase']],
  ['qué tal',["how's it going",'phrase']],
  ['cómo te llamas',["what's your name",'phrase']],
  ['mucho gusto',['nice to meet you','phrase']],
  ['encantado',['nice to meet you','phrase']],
  ['encantada',['nice to meet you','phrase']],
  ['con mucho gusto',['with pleasure','phrase']],
  ['muchas gracias',['thank you very much','phrase']],
  ['de nada',["you're welcome",'phrase']],
  ['por favor',['please','phrase']],
  ['lo siento',["I'm sorry",'phrase']],
  ['no hay problema',['no problem','phrase']],
  ['no importa',["it doesn't matter",'phrase']],
  ['de acuerdo',['agreed/okay','phrase']],
  ['está bien',["it's okay/alright",'phrase']],
  ['muy bien',['very well/very good','phrase']],
  ['buenas noches',['good night','phrase']],
  ['buenos días',['good morning','phrase']],
  ['buenas tardes',['good afternoon','phrase']],
  ['buenas',['hi/good (short greeting)','phrase']],
  ['hasta luego',['see you later','phrase']],
  ['hasta pronto',['see you soon','phrase']],
  ['hasta mañana',['see you tomorrow','phrase']],
  ['nos vemos',["see you/we'll see each other",'phrase']],
  ['me gusta',['I like','phrase']],
  ['me gustan',['I like (plural)','phrase']],
  ['te quiero',['I love you/I care for you','phrase']],
  ['te amo',['I love you','phrase']],
  ['no sé',["I don't know",'phrase']],
  ['no entiendo',["I don't understand",'phrase']],
  ['no comprendo',["I don't understand",'phrase']],
  ['hablas inglés',['do you speak English','phrase']],
  ['habla inglés',['do you speak English (formal)','phrase']],
  ['no hablo español',["I don't speak Spanish",'phrase']],
  ['qué hora es',['what time is it','phrase']],
  ['cuánto cuesta',['how much does it cost','phrase']],
  ['cuánto cuestas',['how much do they cost','phrase']],
  ['dónde está',['where is','phrase']],
  ['dónde están',['where are','phrase']],
  ['cómo se dice',['how do you say','phrase']],
  ['qué significa',['what does it mean','phrase']],
  ['por supuesto',['of course','phrase']],
  ['claro que sí',['of course','phrase']],
  ['a veces',['sometimes','phrase']],
  ['tal vez',['maybe/perhaps','phrase']],
  ['a lo mejor',['maybe/perhaps','phrase']],
  ['más o menos',['more or less','phrase']],
  ['poco a poco',['little by little','phrase']],
  ['de vez en cuando',['from time to time','phrase']],
  ['en realidad',['actually/in reality','phrase']],
  ['sin embargo',['however/nevertheless','phrase']],
  ['a pesar de',['despite/in spite of','phrase']],
  ['en vez de',['instead of','phrase']],
  ['a causa de',['because of','phrase']],
  ['en cuanto a',['as for/regarding','phrase']],
  ['de todos modos',['anyway/regardless','phrase']],
  ['en absoluto',['not at all/absolutely','phrase']],
  ['en seguida',['right away','phrase']],
  ['a menudo',['often','phrase']],
  ['de hecho',['in fact/actually','phrase']],
  ['es decir',['that is/in other words','phrase']],
  ['o sea',['in other words/I mean','phrase']],
  ['por lo tanto',['therefore','phrase']],
  ['por eso',["that's why/therefore",'phrase']],
  ['por ejemplo',['for example','phrase']],
  ['por fin',['finally','phrase']],
  ['por lo menos',['at least','phrase']],
  ['al menos',['at least','phrase']],
  ['al final',['in the end/at the end','phrase']],
  ['al principio',['at the beginning','phrase']],
  ['en general',['in general','phrase']],
  ['en particular',['in particular','phrase']],
  ['en total',['in total','phrase']],
  ['lo que',['what/that which','phrase']],
  ['lo cual',['which','phrase']],
  ['a quien',['to whom','phrase']],
  ['hay que',['one must/it is necessary to','phrase']],
  ['tener que',['to have to','phrase']],
  ['tengo que',['I have to','phrase']],
  ['tienes que',['you have to','phrase']],
  ['tiene que',['has to/you have to (formal)','phrase']],
  ['tenemos que',['we have to','phrase']],
  ['tienen que',['they have to','phrase']],
  ['voy a',["I'm going to",'phrase']],
  ['vas a',["you're going to",'phrase']],
  ['va a',['is going to','phrase']],
  ['vamos a',["we're going to/let's",'phrase']],
  ['van a',['they are going to','phrase']],
  ['acaba de',['has just','phrase']],
  ['acabas de',['you have just','phrase']],
  ['acabo de',['I have just','phrase']],
  ['qué pasa',["what's happening/what's up",'phrase']],
  ['qué pasó',['what happened','phrase']],
  ['qué hay',["what's up",'phrase']],
  ['qué es',['what is','phrase']],
  ['qué son',['what are','phrase']],
  ['quién es',['who is','phrase']],
  ['quiénes son',['who are','phrase']],
  ['cuál es',['which is/what is','phrase']],
  ['cuáles son',['which are/what are','phrase']],

]);
